Repository codestates-seb/seb44_main_031, pull requests merged in 2023-07, with the labels that each got.

#27 ✨feat:산책 상세페이지 레이아웃 구현 완료(2023.07.06 전예훈)
  .github/ISSUE_TEMPLATE/issue-task-card.md
  .github/pull_request_template.md
  client/.eslintrc.json
  client/.gitignore
  client/.prettierrc.json
  client/data/db.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.tsx
  client/src/api/inti.ts
  client/src/assets/Profile.png
  client/src/assets/Undefined.png
  client/src/assets/Walkdog.png
  client/src/assets/map.png
  client/src/assets/react.svg
  client/src/assets/sidedog.png
  client/src/components/init.tsx
  client/src/components/styles/GlobalStyled.ts
  client/src/data/init.tsx
  client/src/features/login-in/LoginIn.tsx
  client/src/features/login-in/loginSlice.tsx
  client/src/features/my-page/Form.tsx
  client/src/features/my-page/Map.tsx
  client/src/features/my-page/MyPage.tsx
  client/src/features/sign-up/SignUp.tsx
  client/src/features/walk-mate-detail/UserCard.tsx
  client/src/features/walk-mate-detail/WalkMateDetail.tsx
  client/src/features/walk-mate-detail/WalkMateDetailBody.tsx
  client/src/features/walk-mate-detail/WalkMateDetailHeader.tsx
  client/src/features/walk-mate-detail/WalkMateDetailSide.tsx
  client/src/hooks/init.tsx
  client/src/main.tsx
  client/src/store/initSlice.ts
  client/src/store/store.ts
  client/src/utils/init.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: [FE] 전예훈, UI

#28 ✨feat: 회원가입 로그인 기능 일부 구현(2023.07.06 박지훈) [
  client/.eslintrc.json
  client/.vscode/extensions.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/styles/GlobalStyled.ts
  client/src/features/login-in/LoginIn.tsx
  client/src/features/login-in/loginSlice.tsx
  client/src/features/sign-in/SignIn.tsx
  client/src/features/sign-in/signInSlice.ts
  client/src/features/sign-up/SignUp.tsx
  client/src/features/sign-up/signUpSlice.ts
  client/src/store/store.ts
Labels: [FE] 박지훈, 기능

#29 ✨ feat: FE 1차 병합 완료 (2023.07.07 이영탁)
  client/data/db.json
  client/index.html
  client/src/App.tsx
  client/src/assets/petmily-logo-pink.png
  client/src/assets/petmily-logo-white.png
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/init.tsx
  client/src/components/styles/StyledButtons.tsx
  client/src/features/sign-in/SignIn.tsx
  client/src/features/sign-up/SignUp.tsx
  client/src/features/walk-mate-all/WalkMateAll.tsx
  client/src/features/walk-mate-create/WalkMateCreate.tsx
  client/src/features/walk-mate-detail/WalkMateDetailBody.tsx
Labels: [FE] 이영탁, UI, 설정

#40 [FE] ✨ feat: 산책 모임 작성 페이지 구현 + 코드리뷰 반영 1차 리팩토링 (2023.07.16 이영탁)
  client/data/walk-mate-create-data.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/walkMateAxios.ts
  client/src/assets/loading-spinner-dog-1.gif
  client/src/assets/loading-spinner-dog-2.gif
  client/src/components/styles/GlobalStyled.ts
  client/src/components/styles/LoaodingSpinner.tsx
  client/src/components/styles/StyledButtons.tsx
  client/src/constants/toastUi.ts
  client/src/features/walk-mate-create/WalkMateCreate.tsx
  client/src/features/walk-mate-create/WalkMateCreateKakaoMap.tsx
  client/src/features/walk-mate-create/WalkMateSelectPetsList.tsx
  client/src/features/walk-mate-create/hooks/useWalkMateForm.ts
  client/src/hooks/init.tsx
  client/src/hooks/useAxios.ts
  client/src/store/store.ts
  client/src/type/global.ts
  client/src/utils/date-utils.ts
  client/src/utils/distance.ts
  client/src/utils/init.tsx
  client/src/utils/kakao-map.ts
  client/tsconfig.json
Labels: [FE] 이영탁, 리팩토링

#46 [FE] ✨ feat: UserCard 기능 구현완료(2023.07.18 전예훈)
  client/data/cards.json
  client/data/comments.json
  client/data/db.json
  client/src/features/walk-mate-detail/UserCard.tsx
  client/src/features/walk-mate-detail/WalkMateDetailBody.tsx
  client/src/features/walk-mate-detail/WalkMateDetailHeader.tsx
  client/vite.config.ts
Labels: [FE] 전예훈, 기능

#48 [FE] ✨ sign-up, log-in 기능구현 마이페이지 일부 기능제외 구현
  client/src/App.tsx
  client/src/features/my-page/AddPetModal.tsx
  client/src/features/my-page/Form.tsx
  client/src/features/my-page/Map.tsx
  client/src/features/my-page/ModifyPasswordModal.tsx
  client/src/features/my-page/ModifyPetModal.tsx
  client/src/features/my-page/MyPage.tsx
  client/src/features/my-page/UsernameChangeModal.tsx
  client/src/features/my-page/myPageSlice.ts
  client/src/features/my-page/useDidMountEffect.tsx
  client/src/features/sign-in/SignIn.tsx
  client/src/features/sign-in/signInSlice.ts
  client/src/features/sign-up/SignUp.tsx
  client/src/features/sign-up/signUpSlice.ts
  client/src/store/store.ts
Labels: [FE] 박지훈, UI, 기능

#51 [FE] ✨ 마이페이지 기능 구현
  client/src/features/my-page/MyPage.tsx
  client/src/features/my-page/myPageSlice.ts
  client/src/features/sign-up/SignUp.tsx
  client/tsconfig.json
Labels: [FE] 박지훈, UI, 기능

#58 [FE] ✨ feat: 메인페이지 기능구현완료 아직 미완(통합테스트위해서 머지) (2023.07.23 전예훈)
  client/data/cards.json
  client/src/App.tsx
  client/src/api/APIurl.ts
  client/src/assets/finddogs.png
  client/src/assets/macbook.png
  client/src/assets/view3.png
  client/src/assets/view4.png
  client/src/assets/viewdog.png
  client/src/components/Main.tsx
  client/src/features/walk-mate-detail/UserCard.tsx
  client/src/features/walk-mate-detail/WalkMateDetailBody.tsx
  client/src/features/walk-mate-detail/WalkMateDetailHeader.tsx
  client/src/features/walk-mate-detail/WalkMateDetailSide.tsx
Labels: [FE] 전예훈, UI, 기능

#60 [FE] ✨ feat: 산책글 전체 조회 페이지 구현 & FE 통합 최종 배포 1차 (2023.07.23 이영탁)
  client/.eslintrc.json
  client/data/walk-mate-all-data.json
  client/data/walk-mate-create-data.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/petmily-logo-pink.png
  client/src/App.tsx
  client/src/api/inti.ts
  client/src/api/reactRouterUrl.ts
  client/src/api/walkMateAxios.ts
  client/src/assets/map-marker-icon-green.png
  client/src/assets/map-marker-icon-red.png
  client/src/components/Footer.tsx
  client/src/components/GuidePage.tsx
  client/src/components/Header.tsx
  client/src/components/styles/GlobalStyled.ts
  client/src/components/styles/LoaodingSpinner.tsx
  client/src/constants/fileSize.ts
  client/src/constants/imageSrcPath.ts
  client/src/constants/toastUi.ts
  client/src/features/my-page/MyPage.tsx
  client/src/features/walk-mate-all/BookmarkIcon.tsx
  client/src/features/walk-mate-all/CopyIcon.tsx
  client/src/features/walk-mate-all/WalkMateAll.tsx
  client/src/features/walk-mate-all/WalkMatesCard.tsx
  client/src/features/walk-mate-all/WalkMatesFilters.tsx
  client/src/features/walk-mate-all/WalkMatesHeader.tsx
  client/src/features/walk-mate-all/WalkMatesMap.tsx
  client/src/features/walk-mate-all/WalkMatesSerchBar.tsx
  client/src/features/walk-mate-all/utils/formattingArticle.ts
  client/src/features/walk-mate-create/WalkMateCreate.tsx
  client/src/features/walk-mate-create/WalkMateCreateKakaoMap.tsx
  client/src/features/walk-mate-create/WalkMateSelectPetsList.tsx
  client/src/features/walk-mate-create/hooks/useWalkMateForm.ts
  client/src/features/walk-mate-detail/UserCard.tsx
  client/src/features/walk-mate-detail/WalkMateDetailBody.tsx
  client/src/features/walk-mate-detail/WalkMateDetailHeader.tsx
  client/src/features/walk-mate-detail/WalkMateDetailSide.tsx
  client/src/hooks/useAxios.ts
  client/src/store/initSlice.ts
  client/src/store/store.ts
  client/src/utils/date-utils.ts
  client/walk-mate-all-data.json
Labels: [FE] 이영탁, UI, 기능, 리팩토링

#63 ♻️ refactor: 토합배포전 수정 (2023.07.24. 전예훈 )
  client/public/assets/hongbo.png
  client/public/assets/iphone.png
  client/src/components/Main.tsx
  client/src/features/my-page/MyPage.tsx
  client/src/features/walk-mate-detail/UserCard.tsx
  client/src/features/walk-mate-detail/WalkMateDetailBody.tsx
  client/src/features/walk-mate-detail/WalkMateDetailHeader.tsx
  client/src/features/walk-mate-detail/WalkMateDetailSide.tsx
Labels: [FE] 전예훈, 리팩토링

#64 ♻️ refactor: 통합배포전 수정 (2023.07.24. 박지훈 ) [FE] 박지훈 리팩토링
  client/src/api/walkMateAxios.ts
  client/src/features/my-page/AddPetModal.tsx
  client/src/features/my-page/Map.tsx
  client/src/features/my-page/MyPage.tsx
  client/src/features/my-page/myPageSlice.ts
  client/src/features/sign-in/LogOut.tsx
  client/src/features/sign-in/SignIn.tsx
  client/src/features/sign-up/SignUp.tsx
  client/src/features/sign-up/signUpSlice.ts
  client/src/features/walk-mate-all/WalkMateAll.tsx
  client/src/features/walk-mate-all/WalkMatesFilters.tsx
  client/src/features/walk-mate-all/utils/formattingArticle.ts
  client/src/features/walk-mate-create/WalkMateCreate.tsx
  client/src/features/walk-mate-create/hooks/useWalkMateForm.ts
Labels: [FE] 박지훈, 리팩토링, 버그

#72 ✨ feat : 마지막 빌드파일 (23.07.22 박지훈)
  .DS_Store
  client/src/features/my-page/MyPage.tsx
  client/src/features/my-page/UserPage.tsx
Labels: [FE] 박지훈, [FE] 이영탁, [FE] 전예훈, 리팩토링
